version: '3.9'
services:
  asir_apache:
    image: 'php:7.4-apache'
    container_name: asir_apache
    ports:
    - '80:80'
    - '8000:8000'
    - '443:443'
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.253
    volumes:
    - ./html:/var/www/html
    - ./confApache:/etc/apache2
  bind9:
    container_name: asir_bind9
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 5300:53/udp
      - 5300:53/tcp
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.254
    volumes:
      - /home/asir2a/Escritorio/SRI/proyectoApache/confDNS/config:/etc/bind
      - /home/asir2a/Escritorio/SRI/proyectoApache/confDNS/zonas:/var/lib/bind
  asir_cliente:
    container_name: asir_cliente
    image: alpine
    networks:
      - bind9_subnet
    stdin_open: true
    tty: true
    dns:
      - 10.1.0.254
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/asir2a/Escritorio/SRI/proyectoApache/confDNS/config:/etc/bind
    ports:
      - 3000:3000 #optional
    restart: unless-stopped
  db:
    image: mysql
    container_name: asir_db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.251
  adminer:
    image: adminer
    container_name: asir_adminer
    ports:
      - 8080:8080
    networks:
      bind9_subnet:
networks:
  bind9_subnet:
    external: true
  